<a href="https://colab.research.google.com/github/marisbotero/ML/blob/master/Ejercicio_regresi%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.formula.api as sm
import statsmodels
from scipy import stats

In [5]:
symbol_data_to_load = ['D','EXC','NEE','SO','DUK']
list_of_df = []


for i in symbol_data_to_load:
    print("Procesando Simbolo: " + i)
    temp_df = pd.read_csv(i+'.csv',sep=',')
    temp_df['Volume_Millions'] = temp_df['Volume'] / 1000000.0
    temp_df['Symbol'] = i # Agregar nueva columna con el simbolo 
    list_of_df.append(temp_df)

print(" --- Completado loop simbolos --- ")
    

agg_df = pd.concat(list_of_df, axis=0)


agg_df['VolStat'] = (agg_df['High'] - agg_df['Low']) / agg_df['Open']
agg_df['Return'] = (agg_df['Close'] / agg_df['Open']) - 1.0




agg_df.head()

Procesando Simbolo: D
Procesando Simbolo: EXC
Procesando Simbolo: NEE
Procesando Simbolo: SO
Procesando Simbolo: DUK
 --- Completado loop simbolos ---

,Date,Open,High,Low,Close,Adj Close,Volume,Volume_Millions,Symbol,VolStat,Return
0,2014-07-28,69.750000,71.059998,69.750000,70.879997,57.963978,1806400,1.8064,D,0.018781,0.016201
1,2014-07-29,70.669998,70.980003,69.930000,69.930000,57.187099,2231100,2.2311,D,0.014858,-0.010471
2,2014-07-30,70.000000,70.660004,68.400002,68.970001,56.402020,2588900,2.5889,D,0.032286,-0.014714
3,2014-07-31,68.629997,68.849998,67.580002,67.639999,55.314388,3266900,3.2669,D,0.018505,-0.014425
4,2014-08-01,67.330002,68.410004,67.220001,67.589996,55.273487,2601800,2.6018,D,0.017674,0.003861

In [4]:
data= agg_df[['Open','High','Low','Close','Volume_Millions','Symbol','VolStat','Return']]
data.head()

,Open,High,Low,Close,Volume_Millions,Symbol,VolStat,Return
0,69.750000,71.059998,69.750000,70.879997,1.8064,D,0.018781,0.016201
1,70.669998,70.980003,69.930000,69.930000,2.2311,D,0.014858,-0.010471
2,70.000000,70.660004,68.400002,68.970001,2.5889,D,0.032286,-0.014714
3,68.629997,68.849998,67.580002,67.639999,3.2669,D,0.018505,-0.014425
4,67.330002,68.410004,67.220001,67.589996,2.6018,D,0.017674,0.003861

In [6]:
def min_max_scaling(series):
    return (series - series.min()) / (series.max() - series.min())
for col in data.columns:
  if col == 'Symbol':
    pass
  else:
    data[col] = min_max_scaling(data[col])
data.head()

,Open,High,Low,Close,Volume_Millions,Symbol,VolStat,Return
0,0.237520,0.241568,0.242309,0.243018,0.048378,D,0.133693,0.774064
1,0.242458,0.241139,0.243286,0.237935,0.064767,D,0.099260,0.567006
2,0.238862,0.239423,0.234985,0.232798,0.078575,D,0.252211,0.534066
3,0.231508,0.229717,0.230536,0.225682,0.104740,D,0.131268,0.536311
4,0.224530,0.227358,0.228582,0.225415,0.079073,D,0.123977,0.678273

In [9]:
model1 = 'VolStat~Open+ High+ Low+ Close + Volume_Millions +Symbol'
lm1   = sm.ols(formula = model1, data = data).fit()
print(lm1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                VolStat   R-squared:                       0.834
Model:                            OLS   Adj. R-squared:                  0.834
Method:                 Least Squares   F-statistic:                     3516.
Date:                Thu, 29 Sep 2022   Prob (F-statistic):               0.00
Time:                        23:12:40   Log-Likelihood:                 14263.
No. Observations:                6295   AIC:                        -2.851e+04
Df Residuals:                    6285   BIC:                        -2.844e+04
Df Model:                           9
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           0.1281      0.001     89.511      0.000       0.125       0.131
Symbol[T.DUK]      -0.0020      0.001     -1.927      0.054      -0.004    3.36e-05
Symbol[T.EXC]      -0.0043      0.001     -3.174      0.002      -0.007      -0.002
Symbol[T.NEE]       0.0072      0.002      4.292      0.000       0.004       0.011
Symbol[T.SO]       -0.0188      0.001    -15.499      0.000      -0.021      -0.016
Open               -0.5613      0.161     -3.478      0.001      -0.878      -0.245
High               17.0916      0.184     92.739      0.000      16.730      17.453
Low               -16.1575      0.184    -87.950      0.000     -16.518     -15.797
Close              -0.4239      0.165     -2.565      0.010      -0.748      -0.100
Volume_Millions     0.1905      0.005     37.250      0.000       0.180       0.201
==============================================================================
Omnibus:                     1459.013   Durbin-Watson:                   1.482
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            32545.425
Skew:                           0.562   Prob(JB):                         0.00
Kurtosis:                      14.082   Cond. No.                     1.11e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.11e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [10]:
model2 = 'Return~Open+ High+ Low+ Close + Volume_Millions +Symbol'
lm2   = sm.ols(formula = model2, data = data).fit()
print(lm2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Return   R-squared:                       0.788
Model:                            OLS   Adj. R-squared:                  0.787
Method:                 Least Squares   F-statistic:                     2589.
Date:                Thu, 29 Sep 2022   Prob (F-statistic):               0.00
Time:                        23:23:00   Log-Likelihood:                 12186.
No. Observations:                6295   AIC:                        -2.435e+04
Df Residuals:                    6285   BIC:                        -2.428e+04
Df Model:                           9
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           0.6495      0.002    326.192      0.000       0.646       0.653
Symbol[T.DUK]       0.0002      0.001      0.158      0.875      -0.003       0.003
Symbol[T.EXC]       0.0010      0.002      0.548      0.584      -0.003       0.005
Symbol[T.NEE]      -0.0006      0.002     -0.255      0.799      -0.005       0.004
Symbol[T.SO]        0.0015      0.002      0.885      0.376      -0.002       0.005
Open              -16.2288      0.224    -72.296      0.000     -16.669     -15.789
High                0.1291      0.256      0.504      0.615      -0.373       0.632
Low                -0.0505      0.256     -0.198      0.843      -0.551       0.450
Close              16.1929      0.230     70.439      0.000      15.742      16.644
Volume_Millions    -0.0142      0.007     -1.992      0.046      -0.028      -0.000
==============================================================================
Omnibus:                     1183.972   Durbin-Watson:                   1.963
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            28613.068
Skew:                          -0.227   Prob(JB):                         0.00
Kurtosis:                      13.435   Cond. No.                     1.11e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.11e+03. This might indicate that there are
strong multicollinearity or other numerical problems.